# Generated by Django 5.1.4 on 2025-07-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
